### PR TITLE
Automatically switch the theme based on a pre defined schedule

### LINKED ISSUE #2: Feature suggestion: automatic mode switching based on time
Many people use something to cover their laptop cameras when not in use, e.g. https://supporters.eff.org/shop/laptop-camera-cover-set

For such people, checking the ambient light is not possible because the camera is covered up most of the time. It would be nice to have a second mechanism to trigger automatic changes based on system time and sunset information.

What do you think?

### PR DESCRIPTION
**Pull request by kleineroscar**
This also fixes #2

### CODE REVIEW

**Comment by Exelord** [comment]
What I think we should do here to close this issue is getting user location by timezone and change the theme based on sunrise/set. What do you think? This way it will be even more automated

**Comment by kleineroscar** [comment]
I agree but we might keep the schedule option for people who block internet connection for atom

**Comment by Exelord** [comment]
We don need internet connection at all :) We know the timezone so we can have estimated position and calculate sunset. Im on it :)

**Comment by Exelord** [comment]
Sun sensor has been implemented :) If you wish to have a scheduled sensor feel free to implement it according to the new sensor api

**Pull request closed without merging**
